- name: Create Azure Resource
  hosts: localhost
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: westus
      tags:
        testing: testing
        delete: never	
